name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn install
      - name: Run build
        run: yarn build
      - name: Run Tests
        run: yarn test
