name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install Dependencies
        run: NODE_OPTIONS='--openssl-legacy-provider' pnpm install
      - name: Build App
        run: pnpm build
      - name: Run Jest Tests
        run: pnpm test
