name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Enable Corepack
        run: corepack enable
      - name: Install Dependencies
        run: NODE_OPTIONS='--openssl-legacy-provider' yarn
      - name: Build App
        run: yarn build
      - name: Run Jest Tests
        run: yarn test
